version: "3.7"

services:
  postgresql:
    image : postgres:latest
    container_name: postgresql
    restart: always
#    expose:
#      - "5432"
    network_mode: host
    env_file: "infrastructures/postgresql/.env"
    volumes:
      - "./infrastructures/postgresql/data:/var/lib/postgresql/data"
  backend:
    build: .
    container_name: "inventory"
    restart: always
    expose:
      - 8000
    env_file: ".env"
    environment:
      - DJANGO_SETTINGS_MODULE=settings.settings
    volumes :
      - "./static:/srv/static"
    depends_on:
      - "postgresql"
  nginx:
    build: "./infrastructures/nginx"
    container_name: "nginx"
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./infrastructures/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./static:/srv/static"
    depends_on:
      - "postgresql"
      - "backend"